name: empreinte_verif
description: Application de vérification par empreinte digitale
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Support empreinte digitale (APK uniquement)
  local_auth: ^2.3.0

  # Ouverture de liens externes
  url_launcher: ^6.2.5

  # Icônes Cupertino / Material
  cupertino_icons: ^1.0.6

  # Backend Supabase (PostgreSQL + API)
  supabase_flutter: ^2.3.4

  # Stockage sécurisé local (pour token si besoin)
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
